config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "books#index"

  resources :books do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy]
  # member do
  #   get :decline
  #   get :accept
  # end

  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: 'pages#dashboard', as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :status, inclusion: { in: ['available', 'booked'] }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :book
  after_create :booked_book_status
  before_destroy :available_book_status

  def booked_book_status
    book.update!(status: "booked")
  end

  def available_book_status
    book.update!(status: "available")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @book = Book.find(params[:book_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @book = Book.find(params[:book_id])
    @booking.user = current_user
    @booking.book = @book
    if @booking.save
      redirect_to book_path(@book)
    else
      render book_path(@book), status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @book = @booking.book
    @booking.destroy
    redirect_to book_path(@book), status: :see_other
  end

  def booking_params
    params.require(:booking).permit(:book_id, :start_date, :end_date, :status)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @books = Book.where(status: "available")
    @books = @books.where.not(user_id: current_user.id) if user_signed_in?
    if user_signed_in?
      @users = User.near(current_user.address, 15)
    else
      @users = User.all
    end

    if params[:query].present?
      sql_subquery = <<~SQL
        books.title @@ :query
        OR books.author @@ :query
      SQL
      @books = @books.where(sql_subquery, query: params[:query])
      @users = User.where(id: @books.pluck(:user_id))
    end

    @markers = @users.geocoded.map do |user|
      {

        lat: user.latitude,
        lng: user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: user}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end


  def show
    @booking = Booking.new
    @book = Book.find(params[:id])
    @user = @book.user
    if @user.geocoded?
    @markers =  [
      {
        lat: @user.latitude,
        lng: @user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: @user}),
        marker_html: render_to_string(partial: "marker")
      }
    ]
  end
end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to dashboard_path
  end

  private

  def book_params
    params.require(:book).permit(:user_id, :title, :author, :summary, :year, :isbn_number, :book_picture, :editor, :status, :photo)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def dashboard
    @books = Book.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_bookingform.html.erb
<div class="bg-white rounded-custom p-3 mt-3 shadow w-50">
  <%= simple_form_for [book, booking], html: { data: { controller: "datepicker" } } do |f| %>
    <%= f.input :start_date, as: :string, input_html: { data: { datepicker_target: "startDateInput" } } %>
    <%= f.input :end_date, as: :string, input_html: { data: { datepicker_target: "endDateInput" } }%>
    <%= f.button :submit, 'Request to borrow', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/books/_form.html.erb
<div class="container my-5 pb-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
        <h2 class="mb-3" >Add a book</h2>
      <div class="bg-white rounded-custom p-3 shadow">
        <%= simple_form_for [book] do |f| %>
          <%= f.input :title,  label: 'Title', placeholder: 'E.g. The Great Gatsby' %>
          <%= f.input :author, label: 'Author', placeholder: 'E.g. F. Scott Fitzgerald'%>
          <%= f.input :year, label: 'Publish date', placeholder: 'E.g. 1925' %>
          <%= f.input :editor, label: 'Publisher', placeholder: 'E.g. Macmillan Educations' %>
          <%= f.input :summary, as: :text, label: 'Summary', placeholder: 'Enter a summary of the book', input_html: { rows: 4 } %>
          <%= f.input :isbn_number, label: 'ISBN', placeholder: 'E.g. 0333791037' %>
          <%= f.input :photo, as: :file, label: 'Add a photo' %>
          <%= f.button :submit, 'Add a book', class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/_info_window.html.erb
<p><%= user.books.first.title.upcase %></p>
<p><%= user.address %></p>

app/views/books/_marker.html.erb
<%= image_tag "marker.png", height: 25, width: 30, alt: "marker", color: "#40E29A"  %>

app/views/books/edit.html.erb
<h1>Edit book</h1>
<%= render "form", book: @book %>

<!-- Tentative d'ajout du formulaire sous forme de modale -->
<!-- <div class="container mt-5">

  <div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Edit your book</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          </button>
        </div>

        <%= simple_form_for [@book] do |f| %>
          <div class="modal-body">
            <%= f.input :title %>
            <%= f.input :author %>
          </div>
          <div class="modal-footer">
            <%= f.submit "Add book", class: "btn btn-flat" %>
            <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div> -->

app/views/books/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.shutterstock.com/image-photo/bokeh-landscape-closeup-left-hand-260nw-2394578275.jpg); backdrop-filter: blur(5px);">
  <div class="container">
    <h1><strong>Find and borrow books from neighbors</strong></h1>
    <div class="row justify-content-center">
      <div class="col-sm-4 my-3">
        <%= form_with url: books_path, method: :get, class: "d-flex"  do %>
          <%= text_field_tag :query,
                  params[:query],
                  class: "form-control", id: "input_field",
                  placeholder: "What's your next read ?"
            %>
          <button type="submit" class="btn btn-success m-0" id="btn_search">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-8 ps-0">
        <div class="cards-container">
          <% @books.each do |book| %>
            <div class="book-card ms-2 mb-3">
              <%= link_to book_path(book), style:"text-decoration: none; color: black" do %>
                <div class="book-card-inner shadow rounded">
                  <div class="book-card-front">
                    <%= image_tag (book.photo.attached? ? cl_image_path(book.photo.key) : 'book_background.png'), class: "rounded", style: "width: 100%; height: 300px; object-fit: cover;" %>
                    <h5 class="card-title mx-3 mt-3"><%= book.title %></h5>
                    <p class="card-text mx-3 mt-1">By <%= book.author %></p>
                  </div>
                  <div class="book-card-back">
                    <div class="text-center pt-4 ps-3 pe-3 pb-4">
                      <p><%= book.summary %></p>
                    </div>
                  </div>
                </div>
              <%end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-4 mt-3 pe-0">
        <div class="sticky-top">
          <div style="width: 100%; height: 600px; border-radius: 8px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>

app/views/books/new.html.erb
<%= render "form", book: @book %>

app/views/books/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-8 row">
      <div class="col-12 mb-3">
        <%= link_to "← Back to books", books_path, style:"text-decoration: none; color: black" %>
      </div>
      <div class="col-5">
        <%= image_tag @book.photo.attached? ? cl_image_path(@book.photo.key) : 'book_background.png',
                      class: "rounded-custom shadow" %>
      </div>
      <div class="col-7" data-controller="toggle-form">
        <h3 class="card-title"><%= @book.title %></h3>
        <div class="d-fle">
          <p class="card-text me-4">By <%= @book.author %></p>
          <p>
            <% if @book.status == "booked" %>
              <span class="badge rounded-pill bg-danger fw-normal">Booked</span>
            <% else %>
              <span class="badge rounded-pill bg-success fw-normal">Available</span>
            <% end %>
          </p>
          <div data-toggle-form-target="form" class="d-none mb-4">
            <%= render "bookingform", book: @book, booking: @booking %>
          </div>
          <!-- Booking Buttons -->
          <div class="mb-3">
            <% if user_signed_in? && @book.user_id != current_user.id %>
              <% booking = @book.bookings.where(user: current_user) %>
              <% if booking.any? %>
                <%= link_to "Cancel the booking", booking_path(booking.first), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger text-light mt-3'  %>
              <% elsif @book.status != "booked" %>
                <%= link_to "Send a booking request", "#", class: 'btn btn-success mt-3', data: { toggle_form_target: "button", action: "click->toggle-form#fire" } %>
              <% end %>
            <% elsif !user_signed_in? && @book.status != "booked" %>
              <%= link_to "Send a booking request", "#", class: 'btn btn-success mt-3', data: { toggle_form_target: "button", action: "click->toggle-form#fire" } %>
            <% end %>
          </div>
          <ul class="list-group list-group-flush bg-white w-fit-content">
            <li class="list-group-item list-group-item-sucess"><strong>Editor:</strong> <%= @book.editor %></li>
            <li class="list-group-item"><strong>Publication year:</strong> <%= @book.year %></li>
            <li class="list-group-item"><strong>ISBN:</strong> <%= @book.isbn_number %></li>
          </ul>
        </div>
      </div>
      <div class="col-12 mt-4">
        <h3>Summary</h3>
        <p class="book-summary col-10"><%= @book.summary%></p>
      </div>
    </div>
    <div class="col-4">
      <div class="sticky-top">
        <div style="width: 100%; height: 600px; border-radius: 8px;"
                data-controller="map"
                data-map-markers-value="<%= @markers.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>

</div>

<% if false %>


<div class="container my-5 d-flex col-10">
  <div class="card mb-3 border-0">
    <div class="row g-0 d-flex">
      <div class="mt-0 mb-4">
        <%= link_to "← Back to books", books_path, style:"text-decoration: none; color: black" %>
      </div>
      <div class="col-md-4 shadow rounded" id="show-image-container">
        <!-- Image -->
        <%= image_tag(@book.photo.attached? ? cl_image_path(@book.photo.key) : 'book_background.png', class: "rounded-custom shadow") %>
      </div>
      <div class="col-md-8">
        <div class="card-body" style="padding-left: 70px;" data-controller="toggle-form">
          <!-- Book informations Section -->
          <h3 class="card-title"><%= @book.title %></h3>
          <div class="d-flex">
            <p class="card-text me-4">By <%= @book.author %></p>
            <p>
              <% if @book.status == "booked" %>
                <span class="badge rounded-pill bg-danger fw-normal">Booked</span>
              <% else %>
                <span class="badge rounded-pill bg-success fw-normal">Available</span>
              <% end %>
            </p>
          </div>
          <!-- Form -->
          <div data-toggle-form-target="form" class="d-none">
            <%= render "bookingform", book: @book, booking: @booking %>
          </div>
          <!-- Booking Buttons -->
          <div>
            <% if user_signed_in? && @book.user_id != current_user.id %>
              <% booking = @book.bookings.where(user: current_user) %>
              <% if booking.any? %>
                <%= link_to "Cancel the booking", booking_path(booking.first), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger text-light mt-3'  %>
              <% elsif @book.status != "booked" %>
                <%= link_to "Send a booking request", "#", class: 'btn btn-success mt-3', data: { toggle_form_target: "button", action: "click->toggle-form#fire" } %>
              <% end %>
            <% elsif !user_signed_in? && @book.status != "booked" %>
              <%= link_to "Send a booking request", "#", class: 'btn btn-success mt-3', data: { toggle_form_target: "button", action: "click->toggle-form#fire" } %>
            <% end %>
          </div>
          <!-- Book Details Section -->
          <div class="row my-4">
            <div class="col">
              <ul class="list-group list-group-flush bg-white" style="width: 229px">
                <li class="list-group-item list-group-item-sucess"><strong>Editor:</strong> <%= @book.editor %></li>
                <li class="list-group-item"><strong>Publication year:</strong> <%= @book.year %></li>
                <li class="list-group-item"><strong>ISBN:</strong> <%= @book.isbn_number %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Book Summary Section -->
    <div class="row my-4">
      <div class="col">
        <h3>Summary</h3>
        <p class="book-summary col-10"><%= @book.summary%></p>
      </div>
    </div>
  </div>
  <div class="col-4 mt-0 pe-0">
    <div class="sticky-top">
      <div style="width: 100%; height: 600px; border-radius: 8px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booknb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container my-5 col-10">

  <div class="dashboard" data-controller="menu-dashboard">
    <div class="div-h1 d-flex">
      <h1>Hello, Martin!</h1>
    </div>
    <div class=" div-button d-flex align-items-start">
      <button class="button-dashboard" data-action="click->menu-dashboard#showBooks"
              data-menu-dashboard-target="myBooksBtn">My Books</button>
      <button class="button-dashboard" data-action="click->menu-dashboard#showBookings"
              data-menu-dashboard-target="bookingsBtn">My Bookings</button>
    </div>
    <!-- Livres ajoutés -->
    <!-- Vous pouvez remplir cette section avec les livres ajoutés -->
    <!-- Livres ajoutés -->
    <!-- Vous pouvez remplir cette section avec les livres ajoutés -->
    <div class="mb-5 mt-3" data-menu-dashboard-target="mybooks">
      <%# <h2 class="my-4 text-start">My Books</h2> %>
      <div class="row">
        <div class="cards-container">
          <% @books.each do |book| %>
            <div class="book-card ms-2 mb-3">
              <div class="book-card-front shadow rounded">
                <%= link_to book_path(book),
                            class: "d-block h-75",
                            style:"
                              text-decoration: none;
                              color: black;
                            " do %>
                  <%= image_tag(book.photo.attached? ? cl_image_path(book.photo.key) : 'book_background.png', class: "card-img-top card_img rounded h-100 object-cover") %>
                <% end %>
                <div class="flex-grow-1 d-flex flex-column justify-content-between">
                  <div class="m-2">
                    <div class="d-flex justify-content-between">
                      <h5 class="card-title"><%= book.title %></h5>
                      <div>
                        <%= link_to edit_book_path(book), style: "text-decoration: none; color: #000000;" do %>
                          <%= content_tag(:i, "", class: "fa-solid fa-pen", style: "color: #000000;") %>
                        <% end %>
                        <%= link_to book_path(book), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, style: "text-decoration: none; color: #000000;" do %>
                          <%= content_tag(:i, "", class: "fa-solid fa-trash", style: "color: #000000;") %>
                        <% end %>
                      </div>
                    </div>
                    <p class="card-text my-2 text-start">
                      <% if book.status == "booked" %>
                        <span class="badge rounded-pill bg-danger fw-normal">Booked</span>
                      <% else %>
                        <span class="badge rounded-pill bg-success fw-normal">Available</span>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Réservations -->
    <div class="mt-3 mb-5" data-menu-dashboard-target="bookings">
      <%# <h2 class="my-4 text-start">My Borrowed Books</h2> %>
      <div class="row">
        <div class="cards-container">
          <% @bookings.each do |booking| %>
            <div class="ms-2 mb-3 book-card">
              <div class="book-card-front-dashboard shadow h-100">
                <%= link_to book_path(booking.book), style:"text-decoration: none; color: black", class: "d-block h-75" do %>
                  <%= image_tag(booking.book.photo.attached? ? cl_image_path(booking.book.photo.key) : 'book_background.png', class: "card-img-top card_img rounded h-100 object-cover") %>
                <% end %>
                <div class="flex-grow-1 d-flex flex-column justify-content-between">
                  <div class="m-2">
                    <h5 class="card-title"><%= booking.book.title %></h5>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div  class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to books_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "navbar-logo", style: "width:225px"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/books", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", "/dashboard", class: "nav-link" %>
          </li>
          <li class="nav-item active ">
            <button type="button" class="btn-navbar tn btn-outline-secondary me-2"><%= link_to "Add a book", new_book_path, class: "nav-link py-0" %></button>
          </li>

          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "avatar.svg", class: "avatar", alt: "dropdown menu" %>
            </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="navbar-filler"></div>